---
ignoreFile: ".thothignore"
production: true
audioFileLocation:
  - test-resources
analyzerThreads: 6
webUiPort: 8080
audibleSearchHost: www.audible.com
audibleAuthorHost: www.audible.com
database:
  driverClassName: "org.h2.Driver"
  jdbcUrl: "jdbc:h2:mem:regular"
  maximumPoolSize: 100
  autoCommit: false
  transactionIsolation: "TRANSACTION_REPEATABLE_READ"
configDirectory: "config"
