---
ignoreFile: ".thothignore"
production: true
audioFileLocations:
  - test-resources
analyzerThreads: 6
port: 8080
audibleSearchHost: www.audible.com
audibleAuthorHost: www.audible.com
database:
  driverClassName: org.sqlite.JDBC
  jdbcUrl: "jdbc:sqlite:./thoth.sqlite"
  maximumPoolSize: 1
  autoCommit: false
  transactionIsolation: "TRANSACTION_REPEATABLE_READ"
configDirectory: "config"