#!/bin/sh

# Get previously staged kotlin files
STAGED_FILES=$(git diff --cached --name-only | while read -r filename; do if [ -f "$filename" ] && [ "${filename##*.}" = "kt" ]; then echo "$filename"; fi; done)
STAGED_FILES_CSV=$(echo "$STAGED_FILES" | paste -sd, -)
if [ -n "$STAGED_FILES" ]; then
    # Run ktfmt on staged files
    ./gradlew ktfmtPrecommit --include-only="$STAGED_FILES_CSV" > /dev/null 2>&1

    # Add formatted files to staging
    echo "$STAGED_FILES" | xargs git add
      echo "Formatting lead to changes. Please review the changes and commit again."
    exit 1
fi