// Generated by jextract

package io.thoth.taglib.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int dummy;
 * }
 * }
 */
public class TagLib_AudioProperties {

    TagLib_AudioProperties() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TagLibC.C_INT.withName("dummy")
    ).withName("TagLib_AudioProperties");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt dummy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dummy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dummy
     * }
     */
    public static final OfInt dummy$layout() {
        return dummy$LAYOUT;
    }

    private static final long dummy$OFFSET = $LAYOUT.byteOffset(groupElement("dummy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dummy
     * }
     */
    public static final long dummy$offset() {
        return dummy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dummy
     * }
     */
    public static int dummy(MemorySegment struct) {
        return struct.get(dummy$LAYOUT, dummy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dummy
     * }
     */
    public static void dummy(MemorySegment struct, int fieldValue) {
        struct.set(dummy$LAYOUT, dummy$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

