// Generated by jextract

package io.thoth.taglib.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     char *mimeType;
 *     char *description;
 *     char *pictureType;
 *     char *data;
 *     unsigned int size;
 * }
 * }
 */
public class TagLib_Complex_Property_Picture_Data {

    TagLib_Complex_Property_Picture_Data() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TagLibC.C_POINTER.withName("mimeType"),
        TagLibC.C_POINTER.withName("description"),
        TagLibC.C_POINTER.withName("pictureType"),
        TagLibC.C_POINTER.withName("data"),
        TagLibC.C_INT.withName("size"),
        MemoryLayout.paddingLayout(4)
    ).withName("TagLib_Complex_Property_Picture_Data");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout mimeType$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mimeType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *mimeType
     * }
     */
    public static final AddressLayout mimeType$layout() {
        return mimeType$LAYOUT;
    }

    private static final long mimeType$OFFSET = $LAYOUT.byteOffset(groupElement("mimeType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *mimeType
     * }
     */
    public static final long mimeType$offset() {
        return mimeType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *mimeType
     * }
     */
    public static MemorySegment mimeType(MemorySegment struct) {
        return struct.get(mimeType$LAYOUT, mimeType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *mimeType
     * }
     */
    public static void mimeType(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mimeType$LAYOUT, mimeType$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final AddressLayout pictureType$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pictureType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *pictureType
     * }
     */
    public static final AddressLayout pictureType$layout() {
        return pictureType$LAYOUT;
    }

    private static final long pictureType$OFFSET = $LAYOUT.byteOffset(groupElement("pictureType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *pictureType
     * }
     */
    public static final long pictureType$offset() {
        return pictureType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *pictureType
     * }
     */
    public static MemorySegment pictureType(MemorySegment struct) {
        return struct.get(pictureType$LAYOUT, pictureType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *pictureType
     * }
     */
    public static void pictureType(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pictureType$LAYOUT, pictureType$OFFSET, fieldValue);
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final OfInt size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int size
     * }
     */
    public static final OfInt size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int size
     * }
     */
    public static int size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int size
     * }
     */
    public static void size(MemorySegment struct, int fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

