// Generated by jextract

package io.thoth.taglib.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class TagLibC extends TagLibC$shared {

    TagLibC() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class taglib_set_strings_unicode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TagLibC.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_set_strings_unicode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void taglib_set_strings_unicode(int unicode)
     * }
     */
    public static FunctionDescriptor taglib_set_strings_unicode$descriptor() {
        return taglib_set_strings_unicode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void taglib_set_strings_unicode(int unicode)
     * }
     */
    public static MethodHandle taglib_set_strings_unicode$handle() {
        return taglib_set_strings_unicode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void taglib_set_strings_unicode(int unicode)
     * }
     */
    public static MemorySegment taglib_set_strings_unicode$address() {
        return taglib_set_strings_unicode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void taglib_set_strings_unicode(int unicode)
     * }
     */
    public static void taglib_set_strings_unicode(int unicode) {
        var mh$ = taglib_set_strings_unicode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_set_strings_unicode", unicode);
            }
            mh$.invokeExact(unicode);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_new {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_new");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * TagLib_File *taglib_file_new(const char *filename)
     * }
     */
    public static FunctionDescriptor taglib_file_new$descriptor() {
        return taglib_file_new.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * TagLib_File *taglib_file_new(const char *filename)
     * }
     */
    public static MethodHandle taglib_file_new$handle() {
        return taglib_file_new.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * TagLib_File *taglib_file_new(const char *filename)
     * }
     */
    public static MemorySegment taglib_file_new$address() {
        return taglib_file_new.ADDR;
    }

    /**
     * {@snippet lang=c :
     * TagLib_File *taglib_file_new(const char *filename)
     * }
     */
    public static MemorySegment taglib_file_new(MemorySegment filename) {
        var mh$ = taglib_file_new.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_new", filename);
            }
            return (MemorySegment)mh$.invokeExact(filename);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void taglib_file_free(TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_file_free$descriptor() {
        return taglib_file_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void taglib_file_free(TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_file_free$handle() {
        return taglib_file_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void taglib_file_free(TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_free$address() {
        return taglib_file_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void taglib_file_free(TagLib_File *file)
     * }
     */
    public static void taglib_file_free(MemorySegment file) {
        var mh$ = taglib_file_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_free", file);
            }
            mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_is_valid {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_INT,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_is_valid");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int taglib_file_is_valid(const TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_file_is_valid$descriptor() {
        return taglib_file_is_valid.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int taglib_file_is_valid(const TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_file_is_valid$handle() {
        return taglib_file_is_valid.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int taglib_file_is_valid(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_is_valid$address() {
        return taglib_file_is_valid.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int taglib_file_is_valid(const TagLib_File *file)
     * }
     */
    public static int taglib_file_is_valid(MemorySegment file) {
        var mh$ = taglib_file_is_valid.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_is_valid", file);
            }
            return (int)mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_audioproperties {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_audioproperties");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const TagLib_AudioProperties *taglib_file_audioproperties(const TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_file_audioproperties$descriptor() {
        return taglib_file_audioproperties.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const TagLib_AudioProperties *taglib_file_audioproperties(const TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_file_audioproperties$handle() {
        return taglib_file_audioproperties.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const TagLib_AudioProperties *taglib_file_audioproperties(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_audioproperties$address() {
        return taglib_file_audioproperties.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const TagLib_AudioProperties *taglib_file_audioproperties(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_audioproperties(MemorySegment file) {
        var mh$ = taglib_file_audioproperties.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_audioproperties", file);
            }
            return (MemorySegment)mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_audioproperties_length {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_INT,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_audioproperties_length");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int taglib_audioproperties_length(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static FunctionDescriptor taglib_audioproperties_length$descriptor() {
        return taglib_audioproperties_length.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int taglib_audioproperties_length(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MethodHandle taglib_audioproperties_length$handle() {
        return taglib_audioproperties_length.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int taglib_audioproperties_length(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MemorySegment taglib_audioproperties_length$address() {
        return taglib_audioproperties_length.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int taglib_audioproperties_length(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static int taglib_audioproperties_length(MemorySegment audioProperties) {
        var mh$ = taglib_audioproperties_length.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_audioproperties_length", audioProperties);
            }
            return (int)mh$.invokeExact(audioProperties);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_audioproperties_bitrate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_INT,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_audioproperties_bitrate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int taglib_audioproperties_bitrate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static FunctionDescriptor taglib_audioproperties_bitrate$descriptor() {
        return taglib_audioproperties_bitrate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int taglib_audioproperties_bitrate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MethodHandle taglib_audioproperties_bitrate$handle() {
        return taglib_audioproperties_bitrate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int taglib_audioproperties_bitrate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MemorySegment taglib_audioproperties_bitrate$address() {
        return taglib_audioproperties_bitrate.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int taglib_audioproperties_bitrate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static int taglib_audioproperties_bitrate(MemorySegment audioProperties) {
        var mh$ = taglib_audioproperties_bitrate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_audioproperties_bitrate", audioProperties);
            }
            return (int)mh$.invokeExact(audioProperties);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_audioproperties_samplerate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_INT,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_audioproperties_samplerate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int taglib_audioproperties_samplerate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static FunctionDescriptor taglib_audioproperties_samplerate$descriptor() {
        return taglib_audioproperties_samplerate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int taglib_audioproperties_samplerate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MethodHandle taglib_audioproperties_samplerate$handle() {
        return taglib_audioproperties_samplerate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int taglib_audioproperties_samplerate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MemorySegment taglib_audioproperties_samplerate$address() {
        return taglib_audioproperties_samplerate.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int taglib_audioproperties_samplerate(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static int taglib_audioproperties_samplerate(MemorySegment audioProperties) {
        var mh$ = taglib_audioproperties_samplerate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_audioproperties_samplerate", audioProperties);
            }
            return (int)mh$.invokeExact(audioProperties);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_audioproperties_channels {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_INT,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_audioproperties_channels");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int taglib_audioproperties_channels(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static FunctionDescriptor taglib_audioproperties_channels$descriptor() {
        return taglib_audioproperties_channels.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int taglib_audioproperties_channels(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MethodHandle taglib_audioproperties_channels$handle() {
        return taglib_audioproperties_channels.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int taglib_audioproperties_channels(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static MemorySegment taglib_audioproperties_channels$address() {
        return taglib_audioproperties_channels.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int taglib_audioproperties_channels(const TagLib_AudioProperties *audioProperties)
     * }
     */
    public static int taglib_audioproperties_channels(MemorySegment audioProperties) {
        var mh$ = taglib_audioproperties_channels.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_audioproperties_channels", audioProperties);
            }
            return (int)mh$.invokeExact(audioProperties);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_property_keys {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_property_keys");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * char **taglib_property_keys(const TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_property_keys$descriptor() {
        return taglib_property_keys.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * char **taglib_property_keys(const TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_property_keys$handle() {
        return taglib_property_keys.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * char **taglib_property_keys(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_property_keys$address() {
        return taglib_property_keys.ADDR;
    }

    /**
     * {@snippet lang=c :
     * char **taglib_property_keys(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_property_keys(MemorySegment file) {
        var mh$ = taglib_property_keys.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_property_keys", file);
            }
            return (MemorySegment)mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_property_get {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_property_get");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * char **taglib_property_get(const TagLib_File *file, const char *prop)
     * }
     */
    public static FunctionDescriptor taglib_property_get$descriptor() {
        return taglib_property_get.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * char **taglib_property_get(const TagLib_File *file, const char *prop)
     * }
     */
    public static MethodHandle taglib_property_get$handle() {
        return taglib_property_get.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * char **taglib_property_get(const TagLib_File *file, const char *prop)
     * }
     */
    public static MemorySegment taglib_property_get$address() {
        return taglib_property_get.ADDR;
    }

    /**
     * {@snippet lang=c :
     * char **taglib_property_get(const TagLib_File *file, const char *prop)
     * }
     */
    public static MemorySegment taglib_property_get(MemorySegment file, MemorySegment prop) {
        var mh$ = taglib_property_get.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_property_get", file, prop);
            }
            return (MemorySegment)mh$.invokeExact(file, prop);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_property_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_property_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void taglib_property_free(char **props)
     * }
     */
    public static FunctionDescriptor taglib_property_free$descriptor() {
        return taglib_property_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void taglib_property_free(char **props)
     * }
     */
    public static MethodHandle taglib_property_free$handle() {
        return taglib_property_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void taglib_property_free(char **props)
     * }
     */
    public static MemorySegment taglib_property_free$address() {
        return taglib_property_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void taglib_property_free(char **props)
     * }
     */
    public static void taglib_property_free(MemorySegment props) {
        var mh$ = taglib_property_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_property_free", props);
            }
            mh$.invokeExact(props);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_pictures {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_pictures");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * TagLib_Complex_Property_Picture_Data **taglib_file_pictures(const TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_file_pictures$descriptor() {
        return taglib_file_pictures.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * TagLib_Complex_Property_Picture_Data **taglib_file_pictures(const TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_file_pictures$handle() {
        return taglib_file_pictures.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * TagLib_Complex_Property_Picture_Data **taglib_file_pictures(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_pictures$address() {
        return taglib_file_pictures.ADDR;
    }

    /**
     * {@snippet lang=c :
     * TagLib_Complex_Property_Picture_Data **taglib_file_pictures(const TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_pictures(MemorySegment file) {
        var mh$ = taglib_file_pictures.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_pictures", file);
            }
            return (MemorySegment)mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_pictures_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_pictures_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void taglib_pictures_free(TagLib_Complex_Property_Picture_Data **pictures)
     * }
     */
    public static FunctionDescriptor taglib_pictures_free$descriptor() {
        return taglib_pictures_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void taglib_pictures_free(TagLib_Complex_Property_Picture_Data **pictures)
     * }
     */
    public static MethodHandle taglib_pictures_free$handle() {
        return taglib_pictures_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void taglib_pictures_free(TagLib_Complex_Property_Picture_Data **pictures)
     * }
     */
    public static MemorySegment taglib_pictures_free$address() {
        return taglib_pictures_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void taglib_pictures_free(TagLib_Complex_Property_Picture_Data **pictures)
     * }
     */
    public static void taglib_pictures_free(MemorySegment pictures) {
        var mh$ = taglib_pictures_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_pictures_free", pictures);
            }
            mh$.invokeExact(pictures);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_file_chapters {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TagLibC.C_POINTER,
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_file_chapters");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * TagLib_Chapter **taglib_file_chapters(TagLib_File *file)
     * }
     */
    public static FunctionDescriptor taglib_file_chapters$descriptor() {
        return taglib_file_chapters.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * TagLib_Chapter **taglib_file_chapters(TagLib_File *file)
     * }
     */
    public static MethodHandle taglib_file_chapters$handle() {
        return taglib_file_chapters.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * TagLib_Chapter **taglib_file_chapters(TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_chapters$address() {
        return taglib_file_chapters.ADDR;
    }

    /**
     * {@snippet lang=c :
     * TagLib_Chapter **taglib_file_chapters(TagLib_File *file)
     * }
     */
    public static MemorySegment taglib_file_chapters(MemorySegment file) {
        var mh$ = taglib_file_chapters.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_file_chapters", file);
            }
            return (MemorySegment)mh$.invokeExact(file);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class taglib_chapters_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TagLibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("taglib_chapters_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void taglib_chapters_free(TagLib_Chapter **chapters)
     * }
     */
    public static FunctionDescriptor taglib_chapters_free$descriptor() {
        return taglib_chapters_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void taglib_chapters_free(TagLib_Chapter **chapters)
     * }
     */
    public static MethodHandle taglib_chapters_free$handle() {
        return taglib_chapters_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void taglib_chapters_free(TagLib_Chapter **chapters)
     * }
     */
    public static MemorySegment taglib_chapters_free$address() {
        return taglib_chapters_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void taglib_chapters_free(TagLib_Chapter **chapters)
     * }
     */
    public static void taglib_chapters_free(MemorySegment chapters) {
        var mh$ = taglib_chapters_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("taglib_chapters_free", chapters);
            }
            mh$.invokeExact(chapters);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

