// Generated by jextract

package io.thoth.taglib.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     char *title;
 *     long long startTime;
 *     long long endTime;
 * }
 * }
 */
public class TagLib_Chapter {

    TagLib_Chapter() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TagLibC.C_POINTER.withName("title"),
        TagLibC.C_LONG_LONG.withName("startTime"),
        TagLibC.C_LONG_LONG.withName("endTime")
    ).withName("TagLib_Chapter");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout title$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *title
     * }
     */
    public static final AddressLayout title$layout() {
        return title$LAYOUT;
    }

    private static final long title$OFFSET = $LAYOUT.byteOffset(groupElement("title"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *title
     * }
     */
    public static final long title$offset() {
        return title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *title
     * }
     */
    public static MemorySegment title(MemorySegment struct) {
        return struct.get(title$LAYOUT, title$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *title
     * }
     */
    public static void title(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(title$LAYOUT, title$OFFSET, fieldValue);
    }

    private static final OfLong startTime$LAYOUT = (OfLong)$LAYOUT.select(groupElement("startTime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long startTime
     * }
     */
    public static final OfLong startTime$layout() {
        return startTime$LAYOUT;
    }

    private static final long startTime$OFFSET = $LAYOUT.byteOffset(groupElement("startTime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long startTime
     * }
     */
    public static final long startTime$offset() {
        return startTime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long startTime
     * }
     */
    public static long startTime(MemorySegment struct) {
        return struct.get(startTime$LAYOUT, startTime$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long startTime
     * }
     */
    public static void startTime(MemorySegment struct, long fieldValue) {
        struct.set(startTime$LAYOUT, startTime$OFFSET, fieldValue);
    }

    private static final OfLong endTime$LAYOUT = (OfLong)$LAYOUT.select(groupElement("endTime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long endTime
     * }
     */
    public static final OfLong endTime$layout() {
        return endTime$LAYOUT;
    }

    private static final long endTime$OFFSET = $LAYOUT.byteOffset(groupElement("endTime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long endTime
     * }
     */
    public static final long endTime$offset() {
        return endTime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long endTime
     * }
     */
    public static long endTime(MemorySegment struct) {
        return struct.get(endTime$LAYOUT, endTime$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long endTime
     * }
     */
    public static void endTime(MemorySegment struct, long fieldValue) {
        struct.set(endTime$LAYOUT, endTime$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

